apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: SelfTest

on:
  push:
    branches:
      - "*"

jobs:
  compat-check:
    #name: Check the action running on CBA
    steps:
      - uses: cloudbees-io/checkout@v1
      - uses: cloudbees-io/configure-aws-credentials@v0
        with:
          aws-region: us-east-1
          aws-access-key-id: ${{ vars.cloudbees_saas_test_access_key_id }}
          aws-secret-access-key: ${{ secrets.cloudbees_saas_test_secret_access_key }}
          role-to-assume: service-eks-role
          role-duration-seconds: "3600" # need to override default of 6h as our role has 1h max
        ## TODO find some way to enable testing this action against the latest docker image on pull requests
      - uses: cloudbees-io/configure-eks-credentials@v0
        with:
          name: saas-test
          alias: mycontext
      - uses: docker://alpine/k8s:1.27.3
        run: |
          kubectl get pods
          kubectl --context mycontext get pods
      - uses: docker://alpine/helm:3.11.1
        run: |
          helm ls
          helm --kube-context mycontext ls
