apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow

name: SelfTest

on:
  push:
    branches:
      - "*"

permissions:
  scm-token-own: read
  scm-token-org: read
  id-token: write

jobs:
  build:
    steps:
      - name: Checkout
        uses: cloudbees-io/checkout@v1

      - name: Validate action
        uses: docker://amazon/aws-cli:2.15.53
        run: |
          TESTING_SHA=$(cat .cloudbees/testing/action.yml | sha1sum)
          ORIGINAL_SHA=$(sed -e 's|docker://public.ecr.aws/l7o7z1g8/actions/|docker://020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/|g' < action.yml | sha1sum)
          if [ "${TESTING_SHA}" != "${ORIGINAL_SHA}" ]; then
            echo "Original action different from testing action"
            exit 1
          fi

      - name: Login to AWS
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.oidc_staging_iam_role }}
          role-duration-seconds: "3600" # optionally set the duration of the login token

      - name: Configure container registry for Staging ECR
        uses: https://github.com/cloudbees-io/configure-ecr-credentials@v1

      - name: Build and publish
        uses: cloudbees-io/kaniko@v1
        with:
          destination: 020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/configure-eks-credentials:${{ cloudbees.scm.sha }},020229604682.dkr.ecr.us-east-1.amazonaws.com/actions/configure-eks-credentials:latest
          labels: maintainer=sdp-pod-3,email=engineering@cloudbees.io

  compat-check:
    needs: ["build"]
    steps:
      - uses: cloudbees-io/checkout@v1
      - name: Login to AWS
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-east-1
          role-to-assume: ${{ vars.oidc_staging_iam_role }}
          role-duration-seconds: "3600" # optionally set the duration of the login token
      - uses: ./.cloudbees/testing
        with:
          name: ${{ vars.tekton_east_cluster_name }}
          alias: mycontext
      - uses: docker://alpine/k8s:1.27.3
        run: |
          kubectl get pods
          kubectl --context mycontext get pods
      - uses: docker://alpine/helm:3.11.1
        run: |
          helm ls
          helm --kube-context mycontext ls

  region-check:
    needs: ["build"]
    steps:
      - uses: cloudbees-io/checkout@v1
      - name: Login to AWS
        uses: cloudbees-io/configure-aws-credentials@v1
        id: aws-login
        with:
          aws-region: us-west-2
          role-to-assume: ${{ vars.oidc_staging_iam_role }}
          role-duration-seconds: "3600" # optionally set the duration of the login token
      - uses: ./.cloudbees/testing
        with:
          name: ${{ vars.tekton_east_cluster_name }}
          alias: mycontext
          region: us-east-1
      - uses: docker://alpine/k8s:1.27.3
        run: |
          kubectl get pods
          kubectl --context mycontext get pods
      - uses: docker://alpine/helm:3.11.1
        run: |
          helm ls
          helm --kube-context mycontext ls
